M48
; DRILL file {KiCad (6.0.4)} date Mon Mar  6 11:12:27 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-06T11:12:27-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.1654Y-2.1654
X2.1654Y-4.5276
X4.5276Y-4.5276
T2
X4.5276Y-2.1654
T0
M30
